<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Idea;

/**
 * IdeaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdeaRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRecentIdeas()
    {
        $em = $this->getEntityManager();
        $queryBuilder = $em->createQueryBuilder();
        $queryBuilder->select(["idea"])
            ->from(Idea::class, "idea")
            ->where("idea.isPublished = 1")
            ->andWhere("idea.dateCreated <= :date_now")
            ->orderBy("idea.dateCreated", "DESC");

        return $queryBuilder->getQuery()->setParameter("date_now", date("Y-m-d H:i:s"))->getResult();
    }

    public function  getIdeaById($id)
    {
        $em = $this->getEntityManager();
        $queryBuilder = $em->createQueryBuilder();
        $queryBuilder->select(["idea"])
            ->from(Idea::class, "idea")
            ->where("idea.id = $id");

        return $queryBuilder->getQuery()->getResult();
    }
}
