<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKnh8oog\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKnh8oog/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerKnh8oog.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerKnh8oog\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerKnh8oog\appProdProjectContainer([
    'container.build_hash' => 'Knh8oog',
    'container.build_id' => 'ae7b5b0e',
    'container.build_time' => 1551877612,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKnh8oog');
