<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';

return $this->services['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(['AppBundle\\Controller\\IdeaController:addAction' => function () {
    return ${($_ = isset($this->services['service_locator.qrc3c0w']) ? $this->services['service_locator.qrc3c0w'] : $this->load('getServiceLocator_Qrc3c0wService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\IdeaController:deleteAction' => function () {
    return ${($_ = isset($this->services['service_locator.7rtdqxt']) ? $this->services['service_locator.7rtdqxt'] : $this->load('getServiceLocator_7rtdqxtService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\IdeaController:editAction' => function () {
    return ${($_ = isset($this->services['service_locator.7rtdqxt']) ? $this->services['service_locator.7rtdqxt'] : $this->load('getServiceLocator_7rtdqxtService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\UserController:loginAction' => function () {
    return ${($_ = isset($this->services['service_locator.skgjfmf']) ? $this->services['service_locator.skgjfmf'] : $this->load('getServiceLocator_SkgjfmfService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\UserController:registerAction' => function () {
    return ${($_ = isset($this->services['service_locator.wp6o_h8']) ? $this->services['service_locator.wp6o_h8'] : $this->load('getServiceLocator_Wp6oH8Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\IdeaController::addAction' => function () {
    return ${($_ = isset($this->services['service_locator.qrc3c0w']) ? $this->services['service_locator.qrc3c0w'] : $this->load('getServiceLocator_Qrc3c0wService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\IdeaController::deleteAction' => function () {
    return ${($_ = isset($this->services['service_locator.7rtdqxt']) ? $this->services['service_locator.7rtdqxt'] : $this->load('getServiceLocator_7rtdqxtService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\IdeaController::editAction' => function () {
    return ${($_ = isset($this->services['service_locator.7rtdqxt']) ? $this->services['service_locator.7rtdqxt'] : $this->load('getServiceLocator_7rtdqxtService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\UserController::loginAction' => function () {
    return ${($_ = isset($this->services['service_locator.skgjfmf']) ? $this->services['service_locator.skgjfmf'] : $this->load('getServiceLocator_SkgjfmfService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\UserController::registerAction' => function () {
    return ${($_ = isset($this->services['service_locator.wp6o_h8']) ? $this->services['service_locator.wp6o_h8'] : $this->load('getServiceLocator_Wp6oH8Service.php')) && false ?: '_'};
}]));
